### ISSUE TITLE
Bar code scanner

### ISSUE THREAD

**Issue by hatemhosny** [KL13NT/badeel#17]
Allow searching products by bar code.

**Comment by KL13NT** [comment]
Thank you for opening this issue, Hatem. How would this function? Would it read the barcode and compare it to a database of available barcodes? Or simply scan the manufacturing country code?

**Comment by hatemhosny** [comment]
Probably both. I can investigate and let you know.

**Comment by hatemhosny** [comment]
It seems to suggest country of origin:

https://www.barcodestalk.com/learn-about-barcodes/resources/barcode-country-codes

https://www.barcoding.com/blog/barcode-prefixes-and-product-country-of-origin

https://internationalbarcodes.com/barcode-country-codes/

https://barcodelive.org/barcode-country-of-origin-list

**Comment by hatemhosny** [comment]
There are APIs for product info, but can be expensive:

https://www.barcodelookup.com/api

https://go-upc.com/plans/api

**Comment by hatemhosny** [comment]
quaggaJS is a JS library for reading barcodes

https://serratus.github.io/quaggaJS/

**Comment by hatemhosny** [comment]
javascript-barcode-reader

https://github.com/mubaidr/Javascript-Barcode-Reader

demo: https://livecodes.io/?x=id/pne4fxr9v4p

**Comment by KL13NT** [comment]
Hey there. After a bit of investigation the only way to actually implement this correctly is to collect product barcode numbers and add them to our database. This is not a problem per se, but it generally requires a lot of effort to collect and implement. I'll be marking this issues as Won't Fix until we decide how we're moving forward with this one. Thank you!
