### ISSUE TITLE
Integrated forms

### ISSUE THREAD

**Issue by hatemhosny** [KL13NT/badeel#20]
Integrated forms for product submission and moderator review.

**Comment by hatemhosny** [comment]
This is an example of submitting forms to google sheets:
https://dev.to/kromate/connecting-your-html-forms-to-a-google-spreadsheet-p9h

**Comment by KL13NT** [comment]
Hello @hatemhosny, thank you for opening this issue. We're currently investigating this approach and I'll be personally trying the link you mentioned. Thank you!

**Comment by hatemhosny** [comment]
Please let me know if you need some help

**Comment by KL13NT** [comment]
Good news 🥳
This feature has been implemented on Badeel in 6d4e83a8b2638d294cacf453449f31fbe98a712f. Thank you for taking the time to suggest this!

**Comment by hatemhosny** [comment]
Nice 👌
