### ISSUE TITLE
no exit from this page & btns are not clickable

### ISSUE THREAD

**Issue by MariamElansary** [KL13NT/badeel#22]
عند الدخول علي صفحة الاسماء لا يمكنني التحرك لاي مكان و كأنها ثقب اسود :)
لا يمكنني الرجوع للصفحة الرئيسية او الضغط علي اي من المنتجات الطريقة الوحيدة للخروج منها هو تغيير ال url!

![image](https://github.com/KL13NT/badeel/assets/5359894/3e2eeec6-9dde-4b67-a69e-679237a7b210)

**Comment by KL13NT** [comment]
Closing as duplicate of #4
