### ISSUE TITLE
add filter to filter for example by support with/againts

### ISSUE THREAD

**Issue by MariamElansary** [KL13NT/badeel#23]
اضافة تصنيف لرؤوس الجدول - مثل تصيف النتائج المعروضة عن الضغط علي الحالة لداعم و مقاطع مثلا

![image](https://github.com/KL13NT/badeel/assets/5359894/58b7f796-0ed5-4316-9d80-fd90d0ebf651)

**Comment by KL13NT** [comment]
تصنيف الحالة مدعوم عن طريق الاختيار الموجود اعلى الموقع, وقيد التغيير دلوقتي في تطويرات الواجهة اللي بنقوم بيها

بالنسبة للجدول نفسه هيتم تغيير الشكل شوية وحالياً مش من اولوياتنا اننا نضيف عليه او نشيل منه, شكراً لتفهمك واقتراحك

**Comment by KL13NT** [comment]
أهلاً بيكي يا @MariamElansary. احنا عملنا إعادة تصميم لواجهة بديل وغيرنا تجربة المستخدم تماماً في موضوع التصنيف والترتيب. دلوقتي الواجهة بالأساس بشكل كروت بسيطة وسهلة القراءة والترتيب والتصنيف من خلال القائمة المخصصة ليها. لو لسه حابه التغيير ده يحصل قوليلي وهفتح الـ issue تاني. شكراً ليكي.
