### ISSUE TITLE
انت الان تظهر seems confusing!

### ISSUE THREAD

**Issue by MariamElansary** [KL13NT/badeel#24]
انت الان تظهر!! اشعر انها مربكة!
![image](https://github.com/KL13NT/badeel/assets/5359894/b2e8ad6c-dee4-4fab-ab1f-1e70a721e9b1)

**Comment by KL13NT** [comment]
احنا حالياً بنقوم بإعادة تصميم واجهة المستخدم في اماكن كتيرة ودي جزء منها. شكراً لاقتراحك.
