### ISSUE TITLE
Font, Images, unneeded text

### ISSUE THREAD

**Issue by MariamElansary** [KL13NT/badeel#26]
بردوا مش issue
جميلة الرسائل و الجمل المعروضة و بتحكي قصص انهم ليست ارقام :)
فكرة جميلة و محفزة .. تعليقات صغيرة علي التصميم .. افضل استخدم الوان علم فلسطين و صور للمسجد الاقصي افضل من الخلفية السوداء و يمكن عرض صور مشهورة للضحايا او تصور AI المعبرة عن المقاطعة سارفق امثلة .. الفونت المستخدم للرسائل  ةالجمل التحفيزية رائع و لكن الفونت العام للتطبيق محتاج يكون افضل مع الحفاظ علي الوضوع 
جمل كا
انت الآن تُظهر
لقد وصلت إلى نهاية القائمة.
يمكن الغاءها

استخدام البطيخ و مثلث فلسطين رائع و الخريطة ايضا
لقد وصلت إلى نهاية القائمة.

![image](https://github.com/KL13NT/badeel/assets/5359894/2dc3dc59-8108-41d8-ae2d-096933a89c78)
![image](https://github.com/KL13NT/badeel/assets/5359894/4c54c512-df31-4ed2-a289-285085183b11)
![WhatsApp Image 2023-11-11 at 23 19 02_fcfce657](https://github.com/KL13NT/badeel/assets/5359894/362a9827-f362-4c0e-8637-ba33a1094a97)
![WhatsApp Image 2023-11-23 at 14 20 39_21ac1524](https://github.com/KL13NT/badeel/assets/5359894/6bef4632-87d1-43ec-b318-cd9927c327f9)
![WhatsApp Image 2023-11-14 at 01 11 23_decc6bc4](https://github.com/KL13NT/badeel/assets/5359894/90b407ba-d293-4b11-893f-e965f9b5cf65)
![image](https://github.com/KL13NT/badeel/assets/5359894/9be5ae10-f618-42c8-856a-b8c1f884a78e)
![image](https://github.com/KL13NT/badeel/assets/5359894/8c8f2594-342b-4082-a615-df8feb79cd1a)
![image](https://github.com/KL13NT/badeel/assets/5359894/cc22b3cc-0a2e-444f-a91b-98c2af08154e)

صورة خير من الف كلمة
شكرا جزيلا
بالتوفيق

**Comment by KL13NT** [comment]
I've forwarded your suggestions to our designed. Thank you!
