### ISSUE TITLE
[Enhancement]_It will be better to have images beside each product 

### ISSUE THREAD

**Issue by ShaimaaMamdouh** [KL13NT/badeel#28]

**Comment by KL13NT** [comment]
Hello @ShaimaaMamdouh, thank you for opening this issue. We understand the importance of having images as visual indicators that would make the search process easier. Unfortunately we won't be introducing images or logos to Badeel as that would add legal concerns which we cannot cover. We hope the redesigned UI makes it easier to read and identify products though! Please let us know what you think of it. Thank you for understanding.

**Comment by ShaimaaMamdouh** [comment]
[like]  Shaimaa Mamdouh reacted to your message:
________________________________
