### ISSUE TITLE
Keep search query even when filtering

### ISSUE THREAD

**Issue by ShaimaaMamdouh** [KL13NT/badeel#30]
https://github.com/KL13NT/badeel/assets/66947673/8cd956ab-c7f7-438a-886a-2ff8783e43c8

It will be better if we can save both the filtration plus the search keywords

**Comment by KL13NT** [comment]
Hello @ShaimaaMamdouh, thank you for opening up this issue. We're currently redesigning the experience and will keep this in mind.

**Comment by KL13NT** [comment]
Good news @ShaimaaMamdouh 🥳, we've redesigned the whole filtering experience. Badeel now always respects your filters and search query and displays them clearly in a tag-like structure for ease of use and continuous visibility. Please let me know what you think of the new UI when you can. Thank you. 🙏
