### ISSUE TITLE
data

### ISSUE THREAD

**Issue by hatemhosny** [KL13NT/badeel#33]
This is some data which you may want to import if you find useful

It includes brand/company name, image/logo, categories and proof

[data.json](https://github.com/KL13NT/badeel/files/13573896/data.json)
Source: https://boycott.thewitness.news/categories

[data-tech.json](https://github.com/KL13NT/badeel/files/13573900/data-tech.json)
Source: https://buyisraelitech.com/

**Comment by KL13NT** [comment]
Hello Hatem, we've already imported most of both databases in our data source. Thank you for the suggestion! :D
