### ISSUE TITLE
Attributes on SVG are ignored

### ISSUE THREAD

**Issue by karimshalapy** [KL13NT/badeel#50]
**Describe the bug**

Whenever I try to pass role, id, or class no error shows in the IDE and the output HTML doesn't contain any of the inputted attributes.

I thought it might be SVGO, so I disabled it entirely, and the same issue exists.

Not sure if I am doing something wrong or if this is something that needs to be addressed.

**To Reproduce**

1. Import any minified SVG as a solid component.
2. Pass any attribute to the SVG component.

**Expected behavior**
The attribute should appear in the compiled DOM tree

**Desktop (please complete the following information if applicable):**
 - OS: Any
 - Browser: Any

**Smartphone (please complete the following information if applicable):**
 - Device: Any
 - OS: Any
 - Browser Any

**Additional context**
I opened an issue on the [vite-plugin-solid-svg](https://github.com/jfgodoy/vite-plugin-solid-svg) repo, and you can find it here: https://github.com/jfgodoy/vite-plugin-solid-svg/issues/43

And as per this [comment](https://github.com/jfgodoy/vite-plugin-solid-svg/issues/43#issuecomment-1870552569), we should update the `vite-plugin-solid-svg`  dependency

**Comment by KL13NT** [comment]
Hey Karim, would you be able to PR a change that adds role="presentation" alt="" to all SVGs imported as well as upgrade the extension?

**Comment by karimshalapy** [comment]
![image](https://github.com/KL13NT/badeel/assets/66819303/383452bf-8684-413b-8082-c11ae4a8cde9)

**Comment by karimshalapy** [comment]
Only one comment here, `role="presentation"` is a synonym to `role="none"` which removes the element's implicit ARIA semantics from being exposed to the accessibility tree. As per [MDN | ARIA: presentation role](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Roles/presentation_role).  

This means that the `alt` is useless here, if you want to add `alt` then we should use `role="img"` and then add a proper `alt` not just an empty string.

**Comment by KL13NT** [comment]
I sent a reply through email but it didn't show up on GitHub for some reason. The alt="" is used as a fallback for screen readers that do not properly interpret aria semantics and attributes.

**Comment by karimshalapy** [comment]
In the [specs](https://www.w3.org/TR/wai-aria-1.1/#presentation), it says:
>Authors SHOULD NOT provide meaningful alternative text (for example, use alt="" in HTML) when the presentation role is applied to an image.

But even then, all we're talking about is the `img` component when it has `role="presentation"`, here it's `svg` not `img` so shouldn't we be good as is?

**Comment by KL13NT** [comment]
I looked more into it:
- alt="" only works on `<img>` 
- alt="" works as fallback for `<img>` for screen readers that cannot process aria properly

So let's stick to only `role="presentation"` :D
