### ISSUE TITLE
[Not an issue]: suggestion to join forces

### ISSUE THREAD

**Issue by hatemhosny** [KL13NT/badeel#52]
Excuse me for opening the issue. This is just a suggestion.

[Tech for Palestine](https://techforpalestine.org/) is an initiative led by Paul Biggar who was a director and co-founder of CircleCI, and was then [fired](https://x.com/paulbiggar/status/1738371292271616220?s=20) after publishing this article: https://blog.paulbiggar.com/i-cant-sleep/

They have launched this initiative and are inviting people to join forces:

https://blog.paulbiggar.com/tech-for-palestine/

https://github.com/TechForPalestine

I just thought you may be interested

**Comment by KL13NT** [comment]
@hatemhosny Hey hey, thanks for opening this discussion. We have been added to the Tech for Palestine project listing on their Discord (a week ago?) thanks to @karimshalapy. The datasets they currently have on GitHub don't really align with this project's goals but we've open to more opportunities! :D
