### ISSUE TITLE
Suggest relevant existing products for users in the submit form

### ISSUE THREAD

**Issue by ahr9n** [KL13NT/badeel#53]
**Is your feature request related to a problem? Please describe.**
Having product duplicates submitted by users who didn't notice that the product is already live on website. This should be some kind of a client validation problem.

**Describe the solution you'd like**
Adding suggestions of relevant products, below the product Arabic name in the submit form, hyperlinked with the product page/view, just like when you open the product details on home page. You can make a full search using tries (all subtrings), or to search on words split contiguous combinations (would be better), or only using the whole name (would be easier). Also, to consider using in-memory cache like Redis, if applicable.

**Comment by KL13NT** [comment]
This is a brilliant idea and I'd love to implement it. I'll work on it as soon as I can.

**Comment by KL13NT** [comment]
Hello @ahr9n, I've implemented an initial version of this on the product submission page. Please try it out and let me know what you think. Thank you for the suggestion!
