### ISSUE TITLE
Support for SSR for SEO enhancement

### ISSUE THREAD

**Issue by imAbdelhadi** [KL13NT/badeel#55]
Hi Badeel Team,
I suggest implementing SSR to improve SEO, leading to better content visibility and search engine indexing.
Best

**Comment by KL13NT** [comment]
Hello @imAbdelhadi, thank you for opening this issue!

As for your request, we currently don't see any value added in adding SSR support relative to the time and value cost it'll incur, and have therefore decided not to move forward with this. The closest consideration we have for this is SSG for the static pages (faq, etc) but that also doesn't have much higher value. Thank you.
