### ISSUE TITLE
Bug: Searching with specific products break the website

### ISSUE THREAD

**Issue by nightmodd** [KL13NT/badeel#63]
**Describe the bug**
The Bug Happens that freezes the whole website any filter or search is not working after the bug just updating the url query.

**To Reproduce**
1. Go to 'website'
2. Search with this value ` "maybeline"` .

**Expected behavior**
suppose to search for the product and if it's not found return null or say there is no product.

**Desktop (please complete the following information if applicable):**
 - Browser : Firefox
 - Version : latest version

**Comment by KL13NT** [comment]
Was data issue lmao
