### ISSUE TITLE
Bug: Google as a backend?

### ISSUE THREAD

**Issue by kemzops** [KL13NT/badeel#65]
So i tested some requests to the google macro(Google Sheets Scripts)... it seems hard to maintain this approach especially  when the website hopefully will get more attention and more people gonna use it in future.

I suggest building a simple back-end to handle and validate the requests even if you guys want to use google sheets as a backend/database maybe? idk really how it works i never used it before but i just wanted to make this issue to make sure everything working well so far without requests spamming.

**TEST REQUEST:**
`POST: https://script.google.com/macros/s/AKfycbxAzl8dtnNQygyZVzzzQOvMP4BiMOZyYoQGGaWd6zYXRgKs-08Z6OGr6i5QBuVZjKOi/exec -> 302 Found`
```
-----------------------------389319358122349470264130689087
Content-Disposition: form-data; name="type"

PRODUCT_TYPE?
-----------------------------389319358122349470264130689087
Content-Disposition: form-data; name="name"

PRODUCT_ARABIC_NAME
-----------------------------389319358122349470264130689087
Content-Disposition: form-data; name="english"

PRODUCT_ENGLISH_NAME
-----------------------------389319358122349470264130689087
Content-Disposition: form-data; name="manufacturer"

COMPANY_NAME
-----------------------------389319358122349470264130689087
Content-Disposition: form-data; name="details"

REASON
-----------------------------389319358122349470264130689087--
```
**RESPONSE:**
```json
{"result":"success","row":141}
```

+ After sending this request there is a new **`GET` `-> OK 200`** request sent automatically with the same **response above**.

**Comment by KL13NT** [comment]
Hello @kemzops, Google Macros don't have a limit for public forms as far as I know. We also fallback to manual submission in case the submission throws an error. We also have plans for whenever we hit a hard limit on the Macro submissions. Thanks for discussing this. 🙂

**Comment by kemzops** [comment]
Yeah i was just wondering about this because these days anything that goes viral it will get attacked at some point... im just making sure everything is going well... Thank you @KL13NT for this project and for all who are involved. :smiley:
