### ISSUE TITLE
Feature Request: Adding authentication functionalities, including login and sign-up 

### ISSUE THREAD

**Issue by mostafasobh** [KL13NT/badeel#70]
**Is your feature request related to a problem? Please describe.**
Adding  authentication functionalities and restricting adding products to the website to loged in users would be helpfull way reduce fraud and to trace back faulty products to the users who added them hence removing them easily, i highly encourage adding this feature, and i would love to volunteer to be the one who add this feature.

**Comment by KL13NT** [comment]
Hello @mostafasobh, products submitted through the form on the website are not automatically added. They're sent to us for verification and then (and only then) do we manually add it to the database. This is clearly stated on the form itself: 
![image](https://github.com/KL13NT/badeel/assets/20807178/c48cabb1-d582-464f-a236-d286a0a2d287)

Thank you.
